#!/usr/bin/env python3
"""
═══════════════════════════════════════════════════════════════════════════════
  live_server.py — Live Dashboard Server            (READ-ONLY · Phase 4)
═══════════════════════════════════════════════════════════════════════════════

  Serves the JP Alpha v3 command center AND a small GET-only JSON endpoint the
  page polls every few seconds, so equity / day-P&L / open-risk / drawdown and
  open-position marks tick in near-real-time — without the browser ever seeing
  the Alpaca keys (they stay here on the server).

  ROUTES
    GET /                → dashboard.html (generated by build_dashboard.py)
    GET /dashboard.html  → same
    GET /api/live        → JSON snapshot { equity, day_pl, open_risk, drawdown,
                           positions[...] } built from GET-only Alpaca calls

  HARD GUARANTEES (same discipline as the rest of the monitoring layer)
    • Imports only build_dashboard.py + analytics.py (both read-only) + stdlib
      + flask.  Places / modifies / cancels ZERO orders.  Writes NO trading
      state.  Every Alpaca call is a GET.
    • The strategy engine (jp_agent.py) is never imported or touched.

  Run behind gunicorn in production (see jp-dashboard.service):
      gunicorn -w 2 -b 0.0.0.0:80 live_server:app
"""

import time
from pathlib import Path
from datetime import datetime
from zoneinfo import ZoneInfo

from flask import Flask, jsonify, send_file, Response
from dotenv import load_dotenv

BASE = Path(__file__).parent
ET = ZoneInfo("America/New_York")
load_dotenv(BASE / ".env")

# Read-only helpers reused from the batch dashboard builder.
import analytics
from build_dashboard import (
    fetch_live, fetch_portfolio_history, enrich_positions, load_json,
)

app = Flask(__name__)

# All-time equity peak, cached so /api/live stays cheap. Used to compute the
# intraday drawdown against the true historical high-water mark. Refreshed at
# most hourly (and immediately surpassed if live equity prints a new high).
_peak = {"pv": 0.0, "ts": 0.0}


def _peak_pv():
    now = time.time()
    if _peak["pv"] <= 0 or (now - _peak["ts"]) > 3600:
        hist = fetch_portfolio_history()
        if hist:
            _peak["pv"] = max(e["pv"] for e in hist)
            _peak["ts"] = now
    return _peak["pv"]


@app.get("/api/live")
def api_live():
    cfg = load_json(BASE / "config.json", {"starting_equity": 100000.0})
    start_eq = float(cfg.get("starting_equity", 100000.0) or 100000.0)
    state = load_json(BASE / "state.json", {"positions": {}})

    acct, positions, clock = fetch_live()
    if not acct:
        return jsonify({"error": "account fetch failed"}), 502

    try:
        pv = float(acct.get("equity") or acct.get("portfolio_value") or 0)
    except (TypeError, ValueError):
        pv = 0.0
    try:
        last_eq = float(acct.get("last_equity", pv) or pv)
    except (TypeError, ValueError):
        last_eq = pv

    day_pl = pv - last_eq
    day_pl_pct = (day_pl / last_eq * 100) if last_eq else 0.0
    total_ret = (pv / start_eq - 1) * 100 if start_eq else 0.0

    enriched = enrich_positions(positions, state)
    car = sum(p.get("risk", 0) or 0 for p in enriched)
    car_pct = (car / pv * 100) if pv else 0.0

    peak = max(_peak_pv(), pv)
    dd_pct = (pv / peak - 1) * 100 if peak else 0.0

    pos = [{
        "symbol": p["symbol"], "dir": p["dir"], "qty": p["qty"],
        "cur": round(p["cur"], 2), "plpc": round(p["plpc"], 2),
    } for p in enriched]

    return jsonify({
        "ts": datetime.now(ET).isoformat(timespec="seconds"),
        "market_open": bool((clock or {}).get("is_open")),
        "equity": round(pv, 2),
        "total_return_pct": round(total_ret, 2),
        "day_pl": round(day_pl, 2),
        "day_pl_pct": round(day_pl_pct, 2),
        "open_risk": round(car, 2),
        "open_risk_pct": round(car_pct, 2),
        "drawdown_pct": round(dd_pct, 2),
        "positions": pos,
    })


@app.get("/")
@app.get("/dashboard.html")
def dashboard():
    f = BASE / "dashboard.html"
    if not f.exists():
        return Response("dashboard.html not generated yet — run build_dashboard.py",
                        status=503, mimetype="text/plain")
    resp = send_file(f, mimetype="text/html")
    resp.headers["Cache-Control"] = "no-store, max-age=0"
    return resp


@app.get("/healthz")
def healthz():
    return jsonify({"ok": True, "ts": datetime.now(ET).isoformat(timespec="seconds")})


if __name__ == "__main__":
    # Dev entrypoint only; production uses gunicorn (see jp-dashboard.service).
    app.run(host="0.0.0.0", port=80)
